"""add_post_views_table

Revision ID: 544afe255498
Revises: a8b3535ff018
Create Date: 2026-05-21 08:07:12.024685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '544afe255498'
down_revision: Union[str, Sequence[str], None] = 'a8b3535ff018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_views', sa.Column('ip_hash', sa.String(length=255), nullable=False))
    op.add_column('post_views', sa.Column('user_agent', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_post_views_ip_hash'), 'post_views', ['ip_hash'], unique=False)
    op.drop_column('post_views', 'viewer_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_views', sa.Column('viewer_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_post_views_ip_hash'), table_name='post_views')
    op.drop_column('post_views', 'user_agent')
    op.drop_column('post_views', 'ip_hash')
    # ### end Alembic commands ###
